name: polkawallet_plugin_statemine
description: A statemine/statemint network plugin for polkawallet.
version: 0.2.9
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.22.0
  get_storage: ^2.0.2
  json_annotation: ^4.0.1
#  polkawallet_sdk: ^0.2.9
  polkawallet_sdk:
    path: ../sdk
  polkawallet_ui:
#    git:
#      url: https://github.com/polkawallet-io/ui.git
#      ref: 144a244b038e56aead4fc97a189057819bfeab08
    path: ../ui

dev_dependencies:
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/statemine.png
    - assets/images/statemine_grey.png
    - assets/images/bg_statemine.png
    - assets/images/tokens/KSM.png
    - assets/images/tokens/DOT.png
